### ISSUE TITLE
Task Review

### ISSUE THREAD

**Issue by GorAlexander** [Pavlo-Momotenko/djangoTestProject#1]
Hi Pavlo!

Thanks for your work on the trial task. In general, looks positive! 
However, we'd like to improve some things that we'll describe and discuss as github issues.

Please, make your code better by:
1. Avoiding duplicate logic, repeated complex transformations
2. Check that variables are named according to their values meaning
3. Use django forms to validate meter data
4. When you do exceptions handling, reduce the try-block to the operations where you expect the exceptions to come from. Other logic should go outside the try-block, or might be related to the next try/except construction.
5. Substitute date parsing by python's std libs tools.
6. Follow Django docs rules on [Where should the tests live?](https://docs.djangoproject.com/en/3.1/topics/testing/overview/) so that running `./manage.py test` could find and exec your tests (it's about `business_logic_unit_tests.py`).

**Comment by Pavlo-Momotenko** [comment]
All of these issues are done ✔️

**Comment by GorAlexander** [comment]
Hi @Pavlo-Momotenko! 
Thanks for your solutions - still there's some space for enhancements, but good overall !
