### ISSUE TITLE
Relative readings expected

### ISSUE THREAD

**Issue by GorAlexander** [Pavlo-Momotenko/djangoTestProject#2]
Hi Pavlo!

In the task we require to calc and display readings as time-relative consumptions, 
e.g. absolute points for Jan 1 = 1001 kWh, Jan 8 = 1025 kWh, Jan 14 = 1032 kWh, (...) should produce relative consumption values:
1. **24 kWh** for the period of Jan 1 - Jan 8
2. **8 kWh** for the period of Jan 8 - Jan 14
3. (...)

**Note 1.** Readings can be overwritten. A new import (period B) should substitute existing readings (period A) only during the overlapping period (intersection of A & B).

**Note 2.** Design a solution tuned to higher performance. Imagine this project would serve thousands of meters with billions of readings. Readings are dates in this task for simplicity, but they could be date-times and more frequent, e.g. of 5-minute resolution. The imported file can contain thousands of records. The requirement is to serve readings import requests and queries for the charts faster. Also, keep in mind, that later we'll need to run complex calculations on readings - totals, averages, costs by tariffs - but this is out of the task's scope.

**Comment by GorAlexander** [comment]
**Note 3.**
Readings imports should work for any periods, independently whether later readings come first, earlier next or vice versa.
The current implementation ignores imports of readings that precede the existing ones in time.

You can use these files (attached) to test the logic:

[test_1.txt](https://github.com/Pavlo-Momotenko/djangoTestProject/files/5787623/test_1.txt)
[test_2.txt](https://github.com/Pavlo-Momotenko/djangoTestProject/files/5787624/test_2.txt)
[test_3.txt](https://github.com/Pavlo-Momotenko/djangoTestProject/files/5787625/test_3.txt)
[test_4.txt](https://github.com/Pavlo-Momotenko/djangoTestProject/files/5787626/test_4.txt)
[test_5.txt](https://github.com/Pavlo-Momotenko/djangoTestProject/files/5787627/test_5.txt)

(these txt files bring csv contents - forced to change the extension due to github limitations on attachment types)

Imports of any file in any order should work. Last file can overwrite readings periods from previous imports.

**Comment by Pavlo-Momotenko** [comment]
Time-relative consumption is done ✔️
