### ISSUE TITLE
Validate imported readings

### ISSUE THREAD

**Issue by GorAlexander** [Pavlo-Momotenko/djangoTestProject#3]
This is the extension for the task (is optional).

Validate CSV data when importing the readings.

- The absolute readings' values are non-decreasing in time. Make sure this consistency is kept after the reading imports.
- Please, display the validation errors in UI with messages that describe the error and CSV line that breaks any of the rules.

**Comment by Pavlo-Momotenko** [comment]
CSV data validation is done ✔️
